{% set version = '2.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-growthcleanr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/growthcleanr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/growthcleanr/growthcleanr_{{ version }}.tar.gz
  sha256: 3b78b3b4d404b0273f95dfd52345332e6656f783313e5bd23faa13c225569772

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.0
    - r-r.utils >=2.11.0
    - r-data.table >=1.13.0
    - r-doparallel >=1.0.15
    - r-dplyr >=1.0.1
    - r-foreach >=1.5.0
    - r-labelled >=2.5.0
    - r-magrittr >=1.5
    - r-plyr >=1.8.6
    - r-tidyr >=1.1.0
  run:
    - r-base
    - r-r.utils >=2.11.0
    - r-data.table >=1.13.0
    - r-doparallel >=1.0.15
    - r-dplyr >=1.0.1
    - r-foreach >=1.5.0
    - r-labelled >=2.5.0
    - r-magrittr >=1.5
    - r-plyr >=1.8.6
    - r-tidyr >=1.1.0

test:
  commands:
    - $R -e "library('growthcleanr')"           # [not win]
    - "\"%R%\" -e \"library('growthcleanr')\""  # [win]

about:
  home: https://carriedaymont.github.io/growthcleanr/index.html, https://github.com/carriedaymont/growthcleanr
  license: MIT
  summary: Identifies implausible anthropometric (e.g., height, weight) measurements in irregularly
    spaced longitudinal datasets, such as those from electronic health records.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: growthcleanr
# Type: Package
# Title: Data Cleaner for Anthropometric Measurements
# Version: 2.2.0
# Authors@R: c( person("Carrie", "Daymont", email = "cdaymont@pennstatehealth.psu.edu", role = c("ctb","cre")), person("Robert", "Grundmeier", role = "aut"), person("Jeffrey", "Miller", role = "aut"), person("Diego", "Campos", role = "aut"), person("Dan", "Chudnov", email = "dlchudnov@mitre.org", role = "ctb"), person("Hannah", "De los Santos", email = "hdelossantos@mitre.org", role = c("ctb")), person("Lusha", "Cao", role = "ctb"), person("Steffani", "Silva", role = "ctb"), person("Hanzhe", "Zhang", role = "ctb"), person("Matt", "Boyas", role = "ctb"), person("David", "Freedman", role = "ctb"), person("Andreas", "Achilleos", role = "ctb"), person("Jessica", "Butts", role = "ctb"), person("Sheila", "Nguyen", role = "ctb"), person("Taraneh", "Soleymani", role = "ctb"), person("Max", "Olivier", role = "ctb") )
# Description: Identifies implausible anthropometric (e.g., height, weight) measurements in irregularly spaced longitudinal datasets, such as those from electronic health records.
# URL: https://carriedaymont.github.io/growthcleanr/index.html, https://github.com/carriedaymont/growthcleanr
# BugReports: https://github.com/carriedaymont/growthcleanr/issues
# Imports: R.utils (>= 2.11.0), data.table (>= 1.13.0), tidyr (>= 1.1.0), plyr (>= 1.8.6), dplyr (>= 1.0.1), foreach (>= 1.5.0), doParallel (>= 1.0.15), labelled (>= 2.5.0), magrittr (>= 1.5)
# Depends: R (>= 2.10)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Suggests: argparser (>= 0.6), bit64 (>= 4.0.2), knitr (>= 1.29), rmarkdown (>= 2.3), testthat (>= 2.3.2)
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2024-02-22 21:16:30 UTC; HDELOSSANTOS
# Author: Carrie Daymont [ctb, cre], Robert Grundmeier [aut], Jeffrey Miller [aut], Diego Campos [aut], Dan Chudnov [ctb], Hannah De los Santos [ctb], Lusha Cao [ctb], Steffani Silva [ctb], Hanzhe Zhang [ctb], Matt Boyas [ctb], David Freedman [ctb], Andreas Achilleos [ctb], Jessica Butts [ctb], Sheila Nguyen [ctb], Taraneh Soleymani [ctb], Max Olivier [ctb]
# Maintainer: Carrie Daymont <cdaymont@pennstatehealth.psu.edu>
# Repository: CRAN
# Date/Publication: 2024-02-26 19:30:02 UTC
